chain/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from index.views import index, login_view, logout, login_historys, page_error, page_not_found, UserPasswordUpdateView

handler404 = page_not_found
handler500 = page_error

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('', index),
    path('index.html', index, name="index"),
    path('login.html', login_view),
    path('logout.html', logout,name="logout"),
    path('password_update.html',UserPasswordUpdateView.as_view() , name="password_update"),
    path('index/login-history.html', login_historys, name="login-history"),
    path('asset/', include('asset.urls', namespace="asset", ), ),
    path('tasks/', include('tasks.urls', namespace="tasks", ), ),
    path('name/', include('name.urls', namespace="name", ), ),
    path('crontab/', include('crontab.urls', namespace="crontabs", ), ),
]

name/urls.py
from django.urls import path
from name import views

urlpatterns = [
    path('name.html', views.NameListAll.as_view(), name='name_list'),
    path('name-add.html', views.NameAdd.as_view(), name='name_add'),
    path('name-all-del.html', views.NameAllDel.as_view(), name='name_all_del'),
    path('name-update-<int:pk>.html', views.NameUpdate.as_view(), name='name_update'),

    path('groups.html', views.GroupListAll.as_view(), name='groups_list'),
    path('groups-add.html', views.GroupsAdd.as_view(), name='groups_add'),
    path('groups-all-del.html', views.GroupsAllDel.as_view(), name='groups_all_del'),
    path('groups-update-<int:pk>.html', views.GroupsUpdate.as_view(), name='groups_update'),

    path('groups-object.html', views.GroupObjectListAll.as_view(), name='groups_object_list'),
    path('groups-object-add.html', views.GroupsObjectAdd.as_view(), name='groups_object_add'),
    path('groups-object-all-del.html', views.GroupsObjectAllDel.as_view(), name='groups_object_all_del'),
    path('groups-object-update-<int:pk>.html', views.GroupsObjectUpdate.as_view(), name='groups_object_update'),
]

app_name = "name"

name/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group
from guardian.models import GroupObjectPermission

__all__ = [
    'Names',
    'Groups',
]


class Names(AbstractUser):
    ps = models.CharField(max_length=1024, verbose_name="备注", null=True, blank=True)

    class Meta:
        db_table = "Names"
        verbose_name = "系统用户管理"
        verbose_name_plural = '系统用户管理'


class Groups(Group):
    ps = models.CharField(max_length=1024, verbose_name="备注", null=True, blank=True)

    @property
    def users(self):
        users = Names.objects.get(groups=self.name)
        return users

    class Meta:
        db_table = "Groups"
        verbose_name = "系统组管理"
        verbose_name_plural = '系统组管理'

name/views.py
from django.shortcuts import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, View, CreateView, UpdateView
from django.urls import reverse_lazy
from name.form import NameForm, GroupsForm, GroupsObjectForm
from name.models import Names, Groups
from guardian.models import GroupObjectPermission
from django.utils.decorators import method_decorator
from guardian.decorators import permission_required_or_404
import json, logging

logger = logging.getLogger('name')


class NameListAll(LoginRequiredMixin, ListView):
    """
    系统用户列表
    """

    template_name = 'name/name.html'
    model = Names
    context_object_name = "name_list"
    queryset = Names.objects.all()
    ordering = ('-id',)

    @method_decorator(permission_required_or_404('name.add_names'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = {
            "name_active": "active",
            "name_list_active": "active",
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)


class NameAdd(LoginRequiredMixin, CreateView):
    """
    系统用户 增加
    """
    model = Names
    form_class = NameForm
    template_name = 'name/name-add-update.html'
    success_url = reverse_lazy('name:name_list')

    @method_decorator(permission_required_or_404('name.add_names'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = {
            "name_active": "active",
            "name_list_active": "active",
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        forms = form.save()
        password_form = form.cleaned_data['password']
        if password_form is not None:
            forms.set_password(password_form)
            forms.save()
        return super().form_valid(form)


class NameUpdate(LoginRequiredMixin, UpdateView):
    """
    系统用户 更新
    """

    model = Names
    form_class = NameForm
    template_name = 'name/name-add-update.html'
    success_url = reverse_lazy('name:name_list')

    @method_decorator(permission_required_or_404('name.change_names'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = {
            "name_active": "active",
            "name_list_active": "active",
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        pk = self.kwargs.get(self.pk_url_kwarg, None)
        obj = Names.objects.get(id=pk)

        old_password = obj.password
        new_password = form.cleaned_data['password']

        forms = form.save()
        if new_password == "1":
            forms.password = old_password
        else:
            forms.set_password(new_password)
        forms.save()
        return super().form_valid(form)


class NameAllDel(LoginRequiredMixin, View):
    """
    系统用户 删除
    """
    model = Names

    @method_decorator(permission_required_or_404('name.delete_names'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    @staticmethod
    def post(request):
        ret = {'status': True, 'error': None, }
        try:
            if request.POST.get('nid'):
                ids = request.POST.get('nid', None)
                Names.objects.get(id=ids).delete()
            else:
                ids = request.POST.getlist('id', None)
                idstring = ','.join(ids)
                Names.objects.extra(
                    where=['id IN (' + idstring + ')']).delete()
        except Exception as e:
            ret['status'] = False
            ret['error'] = '删除请求错误,没有权限{}'.format(e)
        finally:
            return HttpResponse(json.dumps(ret))


class GroupListAll(LoginRequiredMixin, ListView):
    """
    系统组 列表
    """

    template_name = 'name/groups.html'
    model = Groups
    context_object_name = "groups_list"
    queryset = Groups.objects.all()
    ordering = ('-id',)

    @method_decorator(permission_required_or_404('name.add_groups'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = {
            "name_active": "active",
            "groups_list_active": "active",
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)


class GroupsAdd(LoginRequiredMixin, CreateView):
    """
    系统组 增加
    """
    model = Groups
    form_class = GroupsForm
    template_name = 'name/groups-add-update.html'
    success_url = reverse_lazy('name:groups_list')

    @method_decorator(permission_required_or_404('name.add_groups'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = {
            "name_active": "active",
            "groups_list_active": "active",
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)


class GroupsUpdate(LoginRequiredMixin, UpdateView):
    """
    系统组 更新
    """

    model = Groups
    form_class = GroupsForm
    template_name = 'name/groups-add-update.html'
    success_url = reverse_lazy('name:groups_list')

    @method_decorator(permission_required_or_404('name.change_groups'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = {
            "name_active": "active",
            "groups_list_active": "active",
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)


class GroupsAllDel(LoginRequiredMixin, View):
    """
    系统组删除
    """
    model = Groups

    @method_decorator(permission_required_or_404('name.delete_groups'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    @staticmethod
    def post(request):
        ret = {'status': True, 'error': None, }
        try:
            if request.POST.get('nid'):
                ids = request.POST.get('nid', None)
                Groups.objects.get(id=ids).delete()
            else:
                ids = request.POST.getlist('id', None)
                idstring = ','.join(ids)
                Groups.objects.extra(
                    where=['id IN (' + idstring + ')']).delete()
        except Exception as e:
            ret['status'] = False
            ret['error'] = '删除请求错误,没有权限{}'.format(e)
        finally:
            return HttpResponse(json.dumps(ret))


class GroupObjectListAll(LoginRequiredMixin, ListView):
    """
    系统组 对象权限 列表
    """

    template_name = 'name/groups-object.html'
    model = GroupObjectPermission
    context_object_name = "groups_object_list"
    queryset = GroupObjectPermission.objects.all()
    ordering = ('id',)

    @method_decorator(permission_required_or_404('guardian.add_groupobjectpermission'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = {
            "name_active": "active",
            "groups_object_list_active": "active",
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)


class GroupsObjectAdd(LoginRequiredMixin, CreateView):
    """
    系统组对象 增加
    """
    model = GroupObjectPermission
    form_class = GroupsObjectForm
    template_name = 'name/groups-object-add-update.html'
    success_url = reverse_lazy('name:groups_object_list')

    @method_decorator(permission_required_or_404('guardian.add_groupobjectpermission'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = {
            "name_active": "active",
            "groups_object_list_active": "active",
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)

    def form_invalid(self, form):
        print(form.errors)
        return super().form_invalid(form)


class GroupsObjectAllDel(LoginRequiredMixin, View):
    """
    系统组删除
    """
    model = GroupObjectPermission

    @method_decorator(permission_required_or_404('guardian.delete_groupobjectpermission'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    @staticmethod
    def post(request):
        ret = {'status': True, 'error': None, }
        try:
            if request.POST.get('nid'):
                ids = request.POST.get('nid', None)
                GroupObjectPermission.objects.get(id=ids).delete()
            else:
                ids = request.POST.getlist('id', None)
                idstring = ','.join(ids)
                GroupObjectPermission.objects.extra(
                    where=['id IN (' + idstring + ')']).delete()
        except Exception as e:
            ret['status'] = False
            ret['error'] = '删除请求错误,没有权限{}'.format(e)
        finally:
            return HttpResponse(json.dumps(ret))


class GroupsObjectUpdate(LoginRequiredMixin, UpdateView):
    """
    系统组 更新
    """

    model = GroupObjectPermission
    form_class = GroupsObjectForm
    template_name = 'name/groups-object-add-update.html'
    success_url = reverse_lazy('name:groups_object_list')

    @method_decorator(permission_required_or_404('guardian.change_groupobjectpermission'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = {
            "name_active": "active",
            "groups_object_list_active": "active",
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)

templates/name/groups-add-update.html
{% extends "base.html" %}
{% block  title %}登录用户{% endblock %}
{% block header-css %}
{% load bootstrap3 %}
{% endblock %}


{% block page-content %}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>组管理</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a>系统用户</a>
                </li>
                <li class="active">
                    <strong>组管理</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>组管理</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">选项 1</a>
                            </li>
                            <li><a href="#">选项 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">

                    <form enctype="multipart/form-data" method="post" class="form-horizontal" action="">
                        {% csrf_token %}
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger" style="margin: 20px auto 0px">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}

                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-0">
                                <h3>基本</h3>



                                {% bootstrap_field form.name layout="horizontal" %}
                                {% bootstrap_field form.permissions layout="horizontal" %}
                                 {% bootstrap_field form.ps layout="horizontal" %}

                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>


                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-3">

                                {% bootstrap_button "保存" button_type="submit" button_class="btn-primary" %}

                               <a class="btn btn-white" href="{% url "name:groups_list" %}">取消</a>
                            </div>
                        </div>

                    </form>


                </div>
            </div>
        </div>

    </div>


    {% block footer-js %}



        <script>
            $(document).ready(function () {
                $('.select2').select2();
                $("#id_tags").select2({
                    tags: true,
                    {#                                maximumSelectionLength: 8,  //最多能够选择的个数#}
                    closeOnSelect: false
                });
            });



        </script>


    {% endblock %}



{% endblock %}

templates/name/groups-object.html
{% extends "base.html" %}
{% load	bootstrap3 %}
{% load static %}
{% load mytags %}
{% block header-css %}

{% endblock %}

{% block  title %}组管理{% endblock %}



{% block page-content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>权限管理</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url "index" %}">主页</a>
                </li>
                <li>
                    <a>系统用户</a>
                </li>
                <li class="active">
                    <strong>权限管理</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2" id="split-left">

        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">


            <div class="col-lg-12" id="split-right">

                <div class="ibox float-e-margins">

                    <div class="ibox-title">
                        <h5>权限管理</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项 1</a>
                                </li>
                                <li><a href="#">选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">

                            <a href="{% url    'name:groups_object_add' %}"  class="btn btn-sm btn-primary ">添加</a>
                            <a class="btn btn-sm btn-danger  groups_all_del">批量删除</a>

                            <form id="del_form_asset_all" class="form-horizontal">

                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>
                                    <tr>
                                        <th width="20"><input type="checkbox" id="CheckedAll"></th>
                                        <th>组名</th>
                                         <th>权限类型</th>
                                         <th>资产项目</th>
                                        <th>权限</th>

                                        <th>动作</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for   row   in   groups_object_list %}

                                        <tr class="gradeA" id="{{ row.id }}">
                                            <td><input type="checkbox" value="{{ row.id }}" name="id"></td>
                                            <td class="center"> <div class="label label-primary">{{ row.group }}</div></td>
                                            <td class="center"> <div class="label label-success">{{ row.content_type }}</div></td>
                                            <td class="center"> <div class="label label-danger">{{ row.object_pk |  objectasset }}</div></td>
                                            <td class="center"><div class="label label-default"> {{ row.permission }}</div></td>

                                            <td><a class="btn btn-primary  btn-xs " href="{% url  "name:groups_object_update"  pk=row.id %}">编辑</a>
                                                <a class="btn btn-danger  btn-xs  groups_del">删除</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>

                                </table>

                            </form>


                        </div>

                    </div>


                </div>
            </div>
        </div>
    </div>





    {% block footer-js %}


        <script>


            $(function () {

                $(document).on('click', '.groups_del', function () {
                    var id = $(this).parent().parent().attr('id');
                    swal({
                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",
                        closeOnConfirm: false
                    }, function () {
                        $.ajax({
                            url: "/name/groups-object-all-del.html",
                            type: 'POST',
                            data: {'nid': id},
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        });


                    });

                });

                $(document).on('click', '.groups_all_del', function () {

                    swal({

                        title: "你确定删除 权限",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",

                        closeOnConfirm: false
                    }, function () {
                        $.ajax({
                            url: "/name/groups-object-all-del.html",
                            type: 'POST',
                            data: $('#del_form_asset_all').serialize(),
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        });


                    });
                });


            });


        </script>


    {% endblock %}

{% endblock %}

templates/name/groups.html
{% extends "base.html" %}
{% load	bootstrap3 %}
{% load static %}
{% block header-css %}

{% endblock %}

{% block  title %}组管理{% endblock %}



{% block page-content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>组管理</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url "index" %}">主页</a>
                </li>
                <li>
                    <a>系统用户</a>
                </li>
                <li class="active">
                    <strong>组管理</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2" id="split-left">

        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">


            <div class="col-lg-12" id="split-right">

                <div class="ibox float-e-margins">

                    <div class="ibox-title">
                        <h5>组管理</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项 1</a>
                                </li>
                                <li><a href="#">选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">

                            <a href="{% url    'name:groups_add' %}"  class="btn btn-sm btn-primary ">添加</a>
                            <a class="btn btn-sm btn-danger  groups_all_del">批量删除</a>

                            <form id="del_form_asset_all" class="form-horizontal">

                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>
                                    <tr>
                                        <th width="20"><input type="checkbox" id="CheckedAll"></th>
                                        <th>组名</th>
                                        <th>用户</th>
                                         <th>备注</th>

                                        <th>动作</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for   row   in   groups_list %}

                                        <tr class="gradeA" id="{{ row.id }}">
                                            <td><input type="checkbox" value="{{ row.id }}" name="id"></td>
                                            <td class="center">{{ row.name }}</td>
                                              <td class="center">总和:{{ row.user_set.count }} <br>
                                              具体:{% for  i in row.user_set.get_queryset %}{{ i }} | {% endfor %}</td>
                                             <td class="center">{{ row.ps }}</td>

                                            <td><a class="btn btn-primary  btn-xs " href="{% url  "name:groups_update"  pk=row.id %}">编辑</a>
                                                <a class="btn btn-danger  btn-xs  groups_del">删除</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>

                                </table>

                            </form>


                        </div>

                    </div>


                </div>
            </div>
        </div>
    </div>





    {% block footer-js %}


        <script>


            $(function () {

                $(document).on('click', '.groups_del', function () {
                    var id = $(this).parent().parent().attr('id');
                    swal({
                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",
                        closeOnConfirm: false
                    }, function () {
                        $.ajax({
                            url: "/name/groups-all-del.html",
                            type: 'POST',
                            data: {'nid': id},
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        });


                    });

                });

                $(document).on('click', '.groups_all_del', function () {

                    swal({

                        title: "你确定删除 系统组",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",

                        closeOnConfirm: false
                    }, function () {
                        $.ajax({
                            url: "/name/groups-all-del.html",
                            type: 'POST',
                            data: $('#del_form_asset_all').serialize(),
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        });


                    });
                });


            });


        </script>


    {% endblock %}

{% endblock %}