asset/urls.py
from django.urls import path
from asset import views
from asset import api

urlpatterns = [
    path('asset.html', views.AssetListAll.as_view(), name='asset_list'),
    path('asset-add.html', views.AssetAdd.as_view(), name='asset_add'),
    path('asset-all-del.html', views.AssetAllDel.as_view(), name='asset_all_del'),
    path('asset-detail-<int:pk>.html', views.AssetDetail.as_view(), name='asset_detail'),
    path('asset-update-<int:pk>.html', views.AssetUpdate.as_view(), name='asset_update'),

    path('asset-export.html', views.AssetExport.as_view(), name='asset_export'),
    path('asset-import.html', views.AssetImport, name='asset_import'),
    path('asset-ztree.html', views.AssetZtree, name='asset_ztree'),

    path('api/asset.html', api.AssetList.as_view(), name='asset_api_list'),
    path('api/asset-detail-<int:pk>.html', api.AssetDetail.as_view(), name='asset_api_detail'),

    path('asset-user.html', views.AssetUserListAll.as_view(), name='asset_user_list'),
    path('asset-user-add.html', views.AssetUserAdd.as_view(), name='asset_user_add'),
    path('asset-user-all-del.html', views.AssetUserAllDel.as_view(), name='asset_user_all_del'),
    path('asset-user-detail-<int:pk>.html', views.AssetUserDetail.as_view(), name='asset_user_detail'),
    path('asset-user-update-<int:pk>.html', views.AssetUserUpdate.as_view(), name='asset_user_update'),

    path('asset-user-asset-<int:pk>.html', views.AssetUserAsset, name='asset_user_asset'),

    path('asset-webssh.html', views.AssetWeb.as_view(), name='asset_web'),
    path('asset-hardware-update.html', views.AssetHardwareUpdate.as_view(), name='asset_hardware_update'),

    path('asset-project.html', views.AssetProjectListAll.as_view(), name='asset_project_list'),
    path('asset-project-add.html', views.AssetProjectAdd.as_view(), name='asset_project_add'),
    path('asset-project-all-del.html', views.AssetProjectAllDel.as_view(), name='asset_project_all_del'),
    path('asset-project-update-<int:pk>.html', views.AssetProjectUpdate.as_view(), name='asset_project_update'),

    path('asset-business.html', views.AssetBusinessListAll.as_view(), name='asset_business_list'),
    path('asset-business-add.html', views.AssetBusinessAdd.as_view(), name='asset_business_add'),
    path('asset-business-all-del.html', views.AssetBusinessAllDel.as_view(), name='asset_business_all_del'),
    path('asset-business-update-<int:pk>.html', views.AssetBusinessUpdate.as_view(), name='asset_business_update'),
]

app_name = "asset"

chain/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from index.views import index, login_view, logout, login_historys, page_error, page_not_found, UserPasswordUpdateView

handler404 = page_not_found
handler500 = page_error

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('', index),
    path('index.html', index, name="index"),
    path('login.html', login_view),
    path('logout.html', logout,name="logout"),
    path('password_update.html',UserPasswordUpdateView.as_view() , name="password_update"),
    path('index/login-history.html', login_historys, name="login-history"),
    path('asset/', include('asset.urls', namespace="asset", ), ),
    path('tasks/', include('tasks.urls', namespace="tasks", ), ),
    path('name/', include('name.urls', namespace="name", ), ),
    path('crontab/', include('crontab.urls', namespace="crontabs", ), ),
]

name/urls.py
from django.urls import path
from name import views

urlpatterns = [
    path('name.html', views.NameListAll.as_view(), name='name_list'),
    path('name-add.html', views.NameAdd.as_view(), name='name_add'),
    path('name-all-del.html', views.NameAllDel.as_view(), name='name_all_del'),
    path('name-update-<int:pk>.html', views.NameUpdate.as_view(), name='name_update'),

    path('groups.html', views.GroupListAll.as_view(), name='groups_list'),
    path('groups-add.html', views.GroupsAdd.as_view(), name='groups_add'),
    path('groups-all-del.html', views.GroupsAllDel.as_view(), name='groups_all_del'),
    path('groups-update-<int:pk>.html', views.GroupsUpdate.as_view(), name='groups_update'),

    path('groups-object.html', views.GroupObjectListAll.as_view(), name='groups_object_list'),
    path('groups-object-add.html', views.GroupsObjectAdd.as_view(), name='groups_object_add'),
    path('groups-object-all-del.html', views.GroupsObjectAllDel.as_view(), name='groups_object_all_del'),
    path('groups-object-update-<int:pk>.html', views.GroupsObjectUpdate.as_view(), name='groups_object_update'),
]

app_name = "name"

asset/models.py
from django.db import models
import random

__all__ = [
    'AssetInfo',
    'AssetLoginUser',
    'AssetProject'
]


# 登录用户
class AssetLoginUser(models.Model):
    hostname = models.CharField(max_length=64, verbose_name='名称', unique=True)
    username = models.CharField(max_length=64, verbose_name="用户名", default='root', null=True, blank=True)
    password = models.CharField(max_length=256, blank=True, null=True, verbose_name='密码')
    private_key = models.FileField(upload_to='upload/privatekey/%Y%m%d{}'.format(random.randint(0, 99999)),
                                   verbose_name="私钥", null=True, blank=True)
    project = models.ForeignKey(verbose_name='资产项目', to='AssetProject', related_name='project',
                                on_delete=models.SET_NULL, null=True)

    ps = models.CharField(max_length=10240, verbose_name="备注", null=True, blank=True)
    ctime = models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间', blank=True)
    utime = models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间', blank=True)

    class Meta:
        db_table = "AssetLoginUser"
        verbose_name = "资产用户"
        verbose_name_plural = '资产用户'

    def __str__(self):
        return self.hostname


class AssetProject(models.Model):
    projects = models.CharField(max_length=128, verbose_name='资产项目')
    ps = models.CharField(max_length=1024, verbose_name="备注", null=True, blank=True)

    class Meta:
        db_table = "AssetProject"
        verbose_name = "资产项目"
        verbose_name_plural = '资产项目'
        permissions = {
            ('read_assetproject', u"只读资产项目"),
            ('cmd_assetproject', u"执行资产项目"),
        }

    def __str__(self):
        return self.projects

class AssetBusiness(models.Model):
    business = models.CharField(max_length=128, verbose_name='业务')
    ps = models.CharField(max_length=1024, verbose_name="备注", null=True, blank=True)

    class Meta:
        db_table = "AssetBusiness"
        verbose_name = "资产业务"
        verbose_name_plural = '资产业务'

    def __str__(self):
        return self.business


class AssetInfo(models.Model):
    PLATFORM_CHOICES = (
        ("阿里云", "阿里云"),
        ("AWS", "AWS"),
        ("其他", "其他")
    )
    REGION_CHOICES = (
        ("香港", '香港'),
        ("东京", '东京'),
        ("首尔", '首尔'),
        ("华北2", '华北2'),
        ("其他", '其他')
    )

    # id = models.AutoField(primary_key=True, verbose_name="id")
    hostname = models.CharField(max_length=64, verbose_name='主机名', unique=True)
    network_ip = models.GenericIPAddressField(verbose_name='内网IP', unique=True, null=True, blank=True)
    inner_ip = models.GenericIPAddressField(verbose_name='外网IP', null=True, blank=True)
    system = models.CharField(max_length=128, verbose_name='系统版本', null=True, blank=True)
    cpu = models.CharField(max_length=64, verbose_name='CPU', null=True, blank=True)
    memory = models.CharField(max_length=64, verbose_name='内存', null=True, blank=True)
    disk = models.CharField(max_length=256, verbose_name="硬盘", null=True, blank=True)
    bandwidth = models.IntegerField(verbose_name='外网带宽', null=True, blank=True, default="1")
    platform = models.CharField(max_length=128, choices=PLATFORM_CHOICES, verbose_name='平台')
    region = models.CharField(max_length=128, choices=REGION_CHOICES, verbose_name='区域')

    project = models.ForeignKey(verbose_name='资产项目', to='AssetProject', related_name='asset', on_delete=models.CASCADE,)
    business = models.ForeignKey(verbose_name='资产业务', to='AssetBusiness', related_name='asset_business',on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey(verbose_name="登录用户", to='AssetLoginUser', related_name='user_name',
                             on_delete=models.SET_NULL, null=True, blank=True)

    Instance_id = models.CharField(max_length=64, verbose_name='实例ID', null=True, blank=True)

    ps = models.CharField(max_length=1024, verbose_name="备注", null=True, blank=True)
    port = models.IntegerField(verbose_name="登录端口", default='22', null=True, blank=True)
    is_active = models.BooleanField(default=True, verbose_name='激活')

    ctime = models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间', blank=True)
    utime = models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间', blank=True)

    @property
    def users(self):
        users = AssetLoginUser.objects.get(hostname=self.user)
        return users

    class Meta:
        db_table = "AssetInfo"
        verbose_name = "资产管理"
        verbose_name_plural = '资产管理'

    def __str__(self):
        return self.hostname

templates/asset/asset-add-update.html
{% extends "base.html" %}
{% block  title %}资产增改{% endblock %}
{% block header-css %}
    {% load bootstrap3 %}
{% endblock %}


{% block page-content %}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>资产增改</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a href="{% url    'asset:asset_list' %}">资产管理</a>
                </li>
                <li class="active">
                    <strong>资产增改</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>资产增改</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">选项 1</a>
                            </li>
                            <li><a href="#">选项 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">

                    <form enctype="multipart/form-data" method="post" class="form-horizontal" action="">
                        {% csrf_token %}
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger" style="margin: 20px auto 0px">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}

                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-0">
                                <h3>基本</h3>
                                {% bootstrap_field form.hostname layout="horizontal" %}
                                {% bootstrap_field form.network_ip layout="horizontal" %}
                                {% bootstrap_field form.inner_ip layout="horizontal" %}
                                {% bootstrap_field form.platform layout="horizontal" %}
                                {% bootstrap_field form.region layout="horizontal" %}
                                  {% bootstrap_field form.project layout="horizontal" %}
                                {% bootstrap_field form.business layout="horizontal" %}
                                {% bootstrap_field form.user layout="horizontal" %}
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>


                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-0">
                                <h3>可自动获取</h3>
                                {% bootstrap_field form.system layout="horizontal" %}
                                {% bootstrap_field form.cpu layout="horizontal" %}
                                {% bootstrap_field form.memory layout="horizontal" %}
                                {% bootstrap_field form.disk layout="horizontal" %}
                            </div>
                        </div>

                        <input type="hidden" name="__next__" value="{{ i__next__ }}">
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <div class="col-sm-10">
                                <h3>其他</h3>
                                {% bootstrap_field form.Instance_id layout="horizontal" %}
                                {% bootstrap_field form.bandwidth layout="horizontal" %}
                                {% bootstrap_field form.port layout="horizontal" %}
                                {% bootstrap_field form.vars layout="horizontal" %}
                                {% bootstrap_field form.ps layout="horizontal" %}
                                {% bootstrap_field form.is_active layout="horizontal" %}


                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>


                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-3">

                                {% bootstrap_button "保存" button_type="submit" button_class="btn-primary" %}

                                  <a class="btn btn-white" href="{{ i__next__ }}">取消</a>

                            </div>
                        </div>

                    </form>


                </div>
            </div>
        </div>

    </div>


    {% block footer-js %}
        <script>
            $(document).ready(function () {
                $('.select2').select2();
                $("#id_tags").select2({
                    tags: true,
                    {#                                maximumSelectionLength: 8,  //最多能够选择的个数#}
                    closeOnSelect: false
                });
            });

            {#            $('#id_platform').change(function () {#}
            {#                var name = $('#id_platform').val();#}
            {##}
            {#                $.getJSON("{% url 'asset:asset_getdata' %}?name=" + name, function (data, textStatus) {#}
            {##}
            {#                    var content = '';#}
            {#                    $.each(data, function (i, item) {#}
            {#                        content += '<option   value=' + item.pk + '>' + item.fields.name + '</option>'#}
            {#                    });#}
            {#                    $('#id_region').html(content)#}
            {#                });#}
            {#            });#}


        </script>
    {% endblock %}



{% endblock %}

templates/asset/asset-business.html
{% extends "base.html" %}
{% load	bootstrap3 %}
{% load guardian_tags %}
{% load static %}
{% block header-css %}

{% endblock %}

{% block  title %}资产业务{% endblock %}



{% block page-content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>资产业务</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url "index" %}">主页</a>
                </li>
                <li>
                    <a>资产管理</a>
                </li>
                <li class="active">
                    <strong>资产业务</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2" id="split-left">

        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">


            <div class="col-lg-12" id="split-right">

                <div class="ibox float-e-margins">

                    <div class="ibox-title">
                        <h5>资产业务</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项 1</a>
                                </li>
                                <li><a href="#">选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">
                            {% if perms.asset.add_assetbusiness %}
                                <a href="{% url    'asset:asset_business_add' %}" class="btn btn-sm btn-primary ">添加</a>
                            {% endif %}
                            {% if perms.asset.delete_assetbusiness %}
                                <a class="btn btn-sm btn-danger  asset_business_all_del">批量删除</a>{% endif %}
                            <form id="del_form_asset_all" class="form-horizontal">
                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>
                                    <tr>
                                        <th width="20"><input type="checkbox" id="CheckedAll"></th>
                                        <th>业务</th>
                                        <th>备注</th>
                                        <th>动作</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for   row   in   business_list %}

                                        <tr class="gradeA" id="{{ row.id }}">
                                            <td><input type="checkbox" value="{{ row.id }}" name="id"></td>
                                            <td class="center">{{ row.business }}
                                            </td>
                                            <td class="center">{{ row.ps }}</td>
                                            <td>
                                                {% if perms.asset.change_assetbusiness %}
                                                    <a class="btn btn-primary  btn-xs"
                                                       href="{% url  "asset:asset_business_update"  pk=row.id %}">编辑</a>{% endif %}
                                                {% if perms.asset.delete_assetbusiness %}
                                                    <a class="btn btn-danger  btn-xs  asset_business_del">删除</a>{% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>

                                </table>

                            </form>


                        </div>

                    </div>


                </div>
            </div>
        </div>
    </div>





    {% block footer-js %}


        <script>


            $(function () {

                $(document).on('click', '.asset_business_del', function () {
                    var id = $(this).parent().parent().attr('id');
                    swal({
                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",
                        closeOnConfirm: false
                    }, function () {
                        $.ajax({
                            url: "/asset/asset-business-all-del.html",
                            type: 'POST',
                            data: {'nid': id},
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        });


                    });

                });

                $(document).on('click', '.asset_business_all_del', function () {

                    swal({

                        title: "你确定删除 ",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",

                        closeOnConfirm: false
                    }, function () {
                        $.ajax({
                            url: "/asset/asset-business-all-del.html",
                            type: 'POST',
                            data: $('#del_form_asset_all').serialize(),
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        });


                    });
                });


            });


        </script>


    {% endblock %}

{% endblock %}

templates/asset/asset-user-asset.html
{% extends "base.html" %}
{% block  title %}资产用户{% endblock %}
{% block header-css %}

    {% load bootstrap3 %}
{% endblock %}


{% block  page-content %}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>资产用户</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a>资产管理</a>
                </li>
                <li class="active">
                    <strong>管理资产</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="panel-options">
                        <ul class="nav nav-tabs">

                            <li>
                                <a href="{% url  "asset:asset_user_detail"  pk=nid %}" class="text-center"><i
                                        class="fa fa-laptop"></i>资产用户</a>
                            </li>
                            <li class="active">

                                <a class="text-center" href="{% url  "asset:asset_user_asset"   pk=nid %}"><i
                                        class="fa fa-laptop"></i>管理资产</a>
                            </li>


                            <li class="pull-right">
                                <a class="btn btn-outline btn-default"
                                   href="{% url "asset:asset_user_update"  nid %}"><i
                                        class="fa fa-edit"></i>编辑</a>
                            </li>
                            <li class="pull-right">
                                <a class="btn btn-outline btn-danger  asset_user_del">
                                    <i class="fa fa-edit"></i>删除
                                </a>
                            </li>

                        </ul>
                    </div>
                    <div class="ibox-title">
                        <h5>关联资产</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项 1</a>
                                </li>
                                <li><a href="#">选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover dataTables-example">
                                <thead>
                                <tr>

                                    <th>主机名</th>
                                    <th>内网IP</th>
                                    <th>外网IP</th>
                                    <th>平台</th>

                                    <th>项目</th>
                                    <th>动作</th>

                                </tr>
                                </thead>
                                <tbody>

                                {% for   row   in   assets_list %}
                                    <tr class="gradeA" id="{{ row.id }}">

                                        <td class="center"><a
                                                href="{% url  "asset:asset_detail"   pk=row.id %}">{{ row.hostname }}</a>
                                        </td>
                                        <td class="center">{{ row.network_ip }}</td>
                                        <td class="center">{{ row.inner_ip }}</td>
                                        <td class="center">{{ row.platform }} -- {{ row.region }}</td>

                                        <td class="center">{{ row.project }}</td>
                                        <td><a class="btn btn-primary  btn-xs "
                                               href="{% url  "asset:asset_update"  pk=row.id %}">编辑</a>
                                            <a class="btn btn-danger  btn-xs  asset_del"
                                            >删除</a></td>

                                    </tr>
                                {% endfor %}

                                </tbody>
                                <tfoot>
                                <tr>

                                    <th>主机名</th>
                                    <th>外网IP</th>
                                    <th>内网IP</th>
                                    <th>平台</th>

                                    <th>项目</th>
                                    <th>动作</th>

                                </tr>
                                </tfoot>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>




    {% block footer-js %}


        <script>


            $(function () {

                $(document).on('click', '.asset_del', function () {
                    var id = $(this).parent().parent().attr('id');
                    swal({
                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",
                        closeOnConfirm: false
                    }, function () {
                        $.ajax({
                            headers: {"X-CSRFToken": '{{ csrf_token }}'},
                            url: "/asset/asset-all-del.html",
                            type: 'POST',
                            data: {'nid': id},
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        });


                    });

                });


                $('.asset_user_del').click(function () {
                    swal({

                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",
                        closeOnConfirm: false
                    }, function () {
                        $.ajax({
                            url: "/asset/asset-user-all-del.html",
                            type: 'POST',
                            data: {'nid': {{  nid }}},
                            success: function (data) {

                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        location.href = "{% url "asset:asset_list" %}"
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        });


                    });
                });


            });


        </script>


    {% endblock %}


{% endblock %}