asset/urls.py
from django.urls import path
from asset import views
from asset import api

urlpatterns = [
    path('asset.html', views.AssetListAll.as_view(), name='asset_list'),
    path('asset-add.html', views.AssetAdd.as_view(), name='asset_add'),
    path('asset-all-del.html', views.AssetAllDel.as_view(), name='asset_all_del'),
    path('asset-detail-<int:pk>.html', views.AssetDetail.as_view(), name='asset_detail'),
    path('asset-update-<int:pk>.html', views.AssetUpdate.as_view(), name='asset_update'),

    path('asset-export.html', views.AssetExport.as_view(), name='asset_export'),
    path('asset-import.html', views.AssetImport, name='asset_import'),
    path('asset-ztree.html', views.AssetZtree, name='asset_ztree'),

    path('api/asset.html', api.AssetList.as_view(), name='asset_api_list'),
    path('api/asset-detail-<int:pk>.html', api.AssetDetail.as_view(), name='asset_api_detail'),

    path('asset-user.html', views.AssetUserListAll.as_view(), name='asset_user_list'),
    path('asset-user-add.html', views.AssetUserAdd.as_view(), name='asset_user_add'),
    path('asset-user-all-del.html', views.AssetUserAllDel.as_view(), name='asset_user_all_del'),
    path('asset-user-detail-<int:pk>.html', views.AssetUserDetail.as_view(), name='asset_user_detail'),
    path('asset-user-update-<int:pk>.html', views.AssetUserUpdate.as_view(), name='asset_user_update'),

    path('asset-user-asset-<int:pk>.html', views.AssetUserAsset, name='asset_user_asset'),

    path('asset-webssh.html', views.AssetWeb.as_view(), name='asset_web'),
    path('asset-hardware-update.html', views.AssetHardwareUpdate.as_view(), name='asset_hardware_update'),

    path('asset-project.html', views.AssetProjectListAll.as_view(), name='asset_project_list'),
    path('asset-project-add.html', views.AssetProjectAdd.as_view(), name='asset_project_add'),
    path('asset-project-all-del.html', views.AssetProjectAllDel.as_view(), name='asset_project_all_del'),
    path('asset-project-update-<int:pk>.html', views.AssetProjectUpdate.as_view(), name='asset_project_update'),

    path('asset-business.html', views.AssetBusinessListAll.as_view(), name='asset_business_list'),
    path('asset-business-add.html', views.AssetBusinessAdd.as_view(), name='asset_business_add'),
    path('asset-business-all-del.html', views.AssetBusinessAllDel.as_view(), name='asset_business_all_del'),
    path('asset-business-update-<int:pk>.html', views.AssetBusinessUpdate.as_view(), name='asset_business_update'),
]

app_name = "asset"

chain/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from index.views import index, login_view, logout, login_historys, page_error, page_not_found, UserPasswordUpdateView

handler404 = page_not_found
handler500 = page_error

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('', index),
    path('index.html', index, name="index"),
    path('login.html', login_view),
    path('logout.html', logout,name="logout"),
    path('password_update.html',UserPasswordUpdateView.as_view() , name="password_update"),
    path('index/login-history.html', login_historys, name="login-history"),
    path('asset/', include('asset.urls', namespace="asset", ), ),
    path('tasks/', include('tasks.urls', namespace="tasks", ), ),
    path('name/', include('name.urls', namespace="name", ), ),
    path('crontab/', include('crontab.urls', namespace="crontabs", ), ),
]

crontab/urls.py
from django.urls import path
from crontab import views

urlpatterns = [
    path('crontabs.html', views.CrontabsListAll.as_view(), name='crontabs_list'),
    path('crontabs-add.html', views.CrontabsAdd.as_view(), name='crontabs_add'),
    path('crontabs-all-del.html', views.CrontabsAllDel.as_view(), name='crontabs_all_del'),
    path('crontabs-update-<int:pk>.html', views.CrontabsUpdate.as_view(), name='crontabs_update'),

    path('intervals.html', views.IntervalsListAll.as_view(), name='intervals_list'),
    path('intervals-add.html', views.IntervalsAdd.as_view(), name='intervals_add'),
    path('intervals-all-del.html', views.IntervalsAllDel.as_view(), name='intervals_all_del'),
    path('intervals-update-<int:pk>.html', views.IntervalsUpdate.as_view(), name='intervals_update'),

    path('periodictasks.html', views.PeriodicTasksListAll.as_view(), name='periodictasks_list'),
    path('periodictasks-add.html', views.PeriodicTasksAdd.as_view(), name='periodictasks_add'),
    path('periodictasks-all-del.html', views.PeriodicTaskAllDel.as_view(), name='periodictasks_all_del'),
    path('periodictasks-update-<int:pk>.html', views.PeriodicTasksUpdate.as_view(), name='periodictasks_update'),

    path('periodictasks-results.html', views.PeriodicTaskReturnList.as_view(), name='periodictasks_result'),
]



app_name = "crontabs"

name/urls.py
from django.urls import path
from name import views

urlpatterns = [
    path('name.html', views.NameListAll.as_view(), name='name_list'),
    path('name-add.html', views.NameAdd.as_view(), name='name_add'),
    path('name-all-del.html', views.NameAllDel.as_view(), name='name_all_del'),
    path('name-update-<int:pk>.html', views.NameUpdate.as_view(), name='name_update'),

    path('groups.html', views.GroupListAll.as_view(), name='groups_list'),
    path('groups-add.html', views.GroupsAdd.as_view(), name='groups_add'),
    path('groups-all-del.html', views.GroupsAllDel.as_view(), name='groups_all_del'),
    path('groups-update-<int:pk>.html', views.GroupsUpdate.as_view(), name='groups_update'),

    path('groups-object.html', views.GroupObjectListAll.as_view(), name='groups_object_list'),
    path('groups-object-add.html', views.GroupsObjectAdd.as_view(), name='groups_object_add'),
    path('groups-object-all-del.html', views.GroupsObjectAllDel.as_view(), name='groups_object_all_del'),
    path('groups-object-update-<int:pk>.html', views.GroupsObjectUpdate.as_view(), name='groups_object_update'),
]

app_name = "name"

tasks/urls.py
from django.urls import path

from tasks import views

urlpatterns = [
    path('cmd.html', views.TasksCmd.as_view(), name='cmd'),
    path('perform.html', views.TasksPerform.as_view(), name='perform'),

    path('tail.html', views.TasksTail.as_view(), name='tail'),
    path('tailperform.html', views.taskstailperform, name='tail_perform'),
    path('tailperform-stop.html', views.taskstailstopperform, name='tail_perform_stop'),


    path('tools.html', views.ToolsList.as_view(), name='tools'),
    path('tools-add.html', views.ToolsAdd.as_view(), name='tools_add'),
    path('tools-bulk-del.html', views.ToolsAllDel.as_view(), name='tools_bulk_delete'),
    path('tools-update-<int:pk>.html', views.ToolsUpdate.as_view(), name='tools_update'),
    path('tools-exec.html', views.ToolsExec.as_view(), name='tools_exec'),

    path('tools-results.html', views.ToolsResultsList.as_view(), name='tools_results'),
    path('tools-results-detail-<int:pk>.html', views.ToolsResultsDetail.as_view(), name='tools_results_detail'),

    path('vars.html', views.VarsList.as_view(), name='vars'),
    path('vars-add.html', views.VarsAdd.as_view(), name='vars_add'),
    path('vars-bulk-del.html', views.VarsAllDel.as_view(), name='vars_bulk_delete'),
    path('vars-update-<int:pk>.html', views.VarsUpdate.as_view(), name='vars_update'),
]

app_name = "tasks"

templates/_css.html
{% load  static %}

<link href=" {% static  "css/bootstrap.min.css" %}" rel="stylesheet">
<link href="{% static  "font-awesome/css/font-awesome.css" %}" rel="stylesheet">

<link href="{% static  "css/animate.css" %}" rel="stylesheet">
<link href="{% static "css/style.css"  %} " rel="stylesheet">

<link href="{% static "css/datatables.min.css"%} "   rel="stylesheet">

<link href="{% static "css/plugins/select2/select2.min.css"%} "   rel="stylesheet">



<link href="{% static  "css/plugins/sweetalert/sweetalert.css"%}" rel="stylesheet">

<link href="{% static "css/animate.css"%}" rel="stylesheet">
<link href="{% static "css/style.css"%}" rel="stylesheet">


<!-- Toastr style -->
<link  href="{% static  "css/plugins/toastr/toastr.min.css" %}"  rel="stylesheet">

templates/_footer.html
  <div class="footer">
            <div class="pull-right">
               <strong>Version 0.2  Apache v2.</strong>
            </div>
            <div>
                <strong>Copyright</strong> Example Company &copy; 2018-2020
            </div>
        </div>

templates/_js.html
{% load  static %}

<script src="{% static  "js/jquery-3.1.1.min.js"%}"></script>
<script src="{% static  "js/bootstrap.min.js"%}"></script>
<script src="{% static  "js/plugins/metisMenu/jquery.metisMenu.js"%}"></script>
<script src="{% static  "js/plugins/slimscroll/jquery.slimscroll.min.js"%}"></script>

<!-- Custom and plugin javascript -->
<script src="{% static  "js/inspinia.js"%} "></script>
<script src="{% static  "js/plugins/pace/pace.min.js"%}"></script>


<script src="{% static  "js/datatables.min.js" %}"></script>


<script src="{% static  "js/plugins/select2/select2.full.min.js" %}"></script>


<!-- Sweet alert -->
<script src="{% static  "js/plugins/sweetalert/sweetalert.min.js" %}"></script>

 <!-- Toastr script -->
<script src="{% static  "js/plugins/toastr/toastr.min.js"%}"></script>

<script type="text/javascript" src="{% static 'js/plugins/ztree/jquery.ztree.all.min.js' %}"></script>



<!-- Page-Level Scripts -->
<script>
   $(document).ready(function () {



         $('.dataTables-example').DataTable({

            "oLanguage": {
                "sLengthMenu": "每页显示 _MENU_ 条记录",
                "sZeroRecords": "对不起，查询不到任何相关数据",
                "sInfo": "当前显示 _START_ 到 _END_ 条，共 _TOTAL_条记录",
                "sInfoEmtpy": "找不到相关数据",
                "sInfoFiltered": " 数据表中共为 _MAX_ 条记录",
                "sProcessing": "正在加载中...",
                "sSearch": "搜索",
                "oPaginate": {
                    "sFirst": "第一页",
                    "sPrevious": " 上一页 ",
                    "sNext": " 下一页 ",
                    "sLast": " 最后一页 "
                }
            },
            "order": [[1, 'desc']],
            destroy:true,
            columnDefs: [{
                'targets': [0],    //都默认不排序
                'orderable': false
            }],


            dom: '<"html5buttons"B>lTfgitp,',

            buttons: [],
            lengthMenu: [[15, 40, 70, -1], [15, 40, 70, "全部"]]
        });

    });


   $("#CheckedAll").click(function () {
        if ($(this).is(":checked")) {
            $("[name=id]:checkbox").prop("checked", true);
        } else {
            $("[name=id]:checkbox").prop("checked", false);
        }
    });

    </script>

templates/_nav.html
<nav class="navbar-default navbar-static-side  " role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">


                            <span class="clear"> <span class="block m-t-xs"> <strong
                                    class="font-bold">{{ user }}</strong>

                             </span> <span class="text-muted text-xs block">
                                {% ifequal  user.is_superuser  1 %}
                                    管理员 {% else %} 普通用户 {% endifequal %}
                                <b class="caret"></b></span> </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="{% url  "password_update" %}">修改密码</a></li>
                        <li><a href="/logout.html">登出</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    Chain
                </div>
            </li>
            <li>
                <a href="{% url "index" %}"><i class="fa fa-dashboard"></i> <span class="nav-label">首页</span>
                </a>

            </li>
            <li class="{{ asset_active }}">
                <a href="#"><i class="fa fa-inbox"></i> <span class="nav-label">资产管理</span>
                    <span class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li class="{{ asset_list_active }}"><a href="{% url    'asset:asset_list' %}">资产信息</a></li>
                    <li class="{{ asset_user_list_active }}"><a href="{% url    'asset:asset_user_list' %}">资产用户</a></li>
                      <li class="{{ asset_project_list_active }}"><a href="{% url    'asset:asset_project_list' %}">资产项目</a></li>
                     <li class="{{ asset_business_list_active }}"><a href="{% url    'asset:asset_business_list' %}">资产业务</a></li>


                </ul>
            </li>
            <li class="{{ tasks_active }}">
                <a href="#"><i class="fa  fa-coffee"></i> <span class="nav-label">作业中心</span>
                    <span class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li class="{{ tasks_cmd_active }}"><a href="{% url    'tasks:cmd' %}">命令操作</a></li>
                     <li class="{{ tasks_tail_active }}"><a href="{% url    'tasks:tail' %}">日志接口</a></li>
                    <li class="{{ tools_active }}"><a href="{% url    'tasks:tools' %}">脚本工具</a></li>
                    <li class="{{ vars_active }}"><a href="{% url    'tasks:vars' %}">主机变量</a></li>
                    <li class="{{ tools_exec_active }}"><a href="{% url    'tasks:tools_exec' %}">创建任务</a></li>
                    <li class="{{ tools_results_active }}"><a href="{% url    'tasks:tools_results' %}">任务结果</a></li>
                </ul>
            </li>

                    <li class="{{ crontab_active }}">
                <a href="#"><i class="fa  fa-desktop"></i> <span class="nav-label">定时任务</span>
                    <span class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li class="{{ crontab_crontabs_active }}"><a href="{% url    'crontabs:crontabs_list' %}">定时时间</a></li>
                     <li class="{{ crontab_intervals_active }}"><a href="{% url    'crontabs:intervals_list' %}">时间间隔</a></li>
                      <li class="{{ crontab_periodictasks_active }}"><a href="{% url    'crontabs:periodictasks_list' %}">周期任务</a></li>
                     <li class="{{ crontab_periodictasks_result_active }}"><a href="{% url    'crontabs:periodictasks_result' %}">周期结果</a></li>
                </ul>

            </li>


         {% ifequal  user.is_superuser  1 %}
            <li class="{{ name_active }}">
                <a href="#"><i class="fa fa-group"></i> <span class="nav-label">系统用户</span>
                    <span class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li class="{{ name_list_active }}"><a href="{% url  'name:name_list' %}">用户管理</a></li>
                      <li class="{{ groups_list_active }}"><a href="{% url  'name:groups_list' %}">组管理</a></li>
                     <li class="{{  groups_object_list_active }}"><a href="{% url  'name:groups_object_list' %}">权限管理</a></li>


                </ul>
            </li>

            <li class="{{ index_active }}">
                <a href="#"><i class="fa fa-gears"></i> <span class="nav-label">后台管理</span>
                    <span class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li class="{{ index_login_active }}"><a href="{% url  'login-history' %}">平台登录</a></li>
                    <li><a href="/admin" target="_blank">管理界面</a></li>

                </ul>
            </li>
        {% endifequal %}
        </ul>

    </div>
</nav>

templates/_navbar-static-top.html
<div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    欢迎 {{ user  }} 使用 链喵  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                    <li>
                        <a href="/logout.html">
                            <i class="fa fa-sign-out"></i> 注销
                        </a>
                    </li>
                </ul>

            </nav>
        </div>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link rel="shortcut icon" href="{%  static  "demo/favicon.ico"%}" type="image/x-icon" />

    <title>{% block  title %}{% endblock %}</title>

    {% include  "_css.html" %}
    {% block header-css %}
    {% endblock %}


</head>

<body>
<div id="wrapper" class="container1">


    {% include "_nav.html" %}

    <div id="page-wrapper" class="gray-bg">
        {% include  "_navbar-static-top.html" %}

        {% block page-content %}


        {% endblock %}
        {% include  "_footer.html" %}

    </div>
</div>


<div id="terminal"></div>

{% include  "_js.html" %}
{% block footer-js %}

{% endblock %}

{% block footer-js-ajax %}
    <script type="text/JavaScript">
        $.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});
    </script>
{% endblock %}
</body>

</html>