chain/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from index.views import index, login_view, logout, login_historys, page_error, page_not_found, UserPasswordUpdateView

handler404 = page_not_found
handler500 = page_error

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('', index),
    path('index.html', index, name="index"),
    path('login.html', login_view),
    path('logout.html', logout,name="logout"),
    path('password_update.html',UserPasswordUpdateView.as_view() , name="password_update"),
    path('index/login-history.html', login_historys, name="login-history"),
    path('asset/', include('asset.urls', namespace="asset", ), ),
    path('tasks/', include('tasks.urls', namespace="tasks", ), ),
    path('name/', include('name.urls', namespace="name", ), ),
    path('crontab/', include('crontab.urls', namespace="crontabs", ), ),
]

name/urls.py
from django.urls import path
from name import views

urlpatterns = [
    path('name.html', views.NameListAll.as_view(), name='name_list'),
    path('name-add.html', views.NameAdd.as_view(), name='name_add'),
    path('name-all-del.html', views.NameAllDel.as_view(), name='name_all_del'),
    path('name-update-<int:pk>.html', views.NameUpdate.as_view(), name='name_update'),

    path('groups.html', views.GroupListAll.as_view(), name='groups_list'),
    path('groups-add.html', views.GroupsAdd.as_view(), name='groups_add'),
    path('groups-all-del.html', views.GroupsAllDel.as_view(), name='groups_all_del'),
    path('groups-update-<int:pk>.html', views.GroupsUpdate.as_view(), name='groups_update'),

    path('groups-object.html', views.GroupObjectListAll.as_view(), name='groups_object_list'),
    path('groups-object-add.html', views.GroupsObjectAdd.as_view(), name='groups_object_add'),
    path('groups-object-all-del.html', views.GroupsObjectAllDel.as_view(), name='groups_object_all_del'),
    path('groups-object-update-<int:pk>.html', views.GroupsObjectUpdate.as_view(), name='groups_object_update'),
]

app_name = "name"

tasks/urls.py
from django.urls import path

from tasks import views

urlpatterns = [
    path('cmd.html', views.TasksCmd.as_view(), name='cmd'),
    path('perform.html', views.TasksPerform.as_view(), name='perform'),

    path('tail.html', views.TasksTail.as_view(), name='tail'),
    path('tailperform.html', views.taskstailperform, name='tail_perform'),
    path('tailperform-stop.html', views.taskstailstopperform, name='tail_perform_stop'),


    path('tools.html', views.ToolsList.as_view(), name='tools'),
    path('tools-add.html', views.ToolsAdd.as_view(), name='tools_add'),
    path('tools-bulk-del.html', views.ToolsAllDel.as_view(), name='tools_bulk_delete'),
    path('tools-update-<int:pk>.html', views.ToolsUpdate.as_view(), name='tools_update'),
    path('tools-exec.html', views.ToolsExec.as_view(), name='tools_exec'),

    path('tools-results.html', views.ToolsResultsList.as_view(), name='tools_results'),
    path('tools-results-detail-<int:pk>.html', views.ToolsResultsDetail.as_view(), name='tools_results_detail'),

    path('vars.html', views.VarsList.as_view(), name='vars'),
    path('vars-add.html', views.VarsAdd.as_view(), name='vars_add'),
    path('vars-bulk-del.html', views.VarsAllDel.as_view(), name='vars_bulk_delete'),
    path('vars-update-<int:pk>.html', views.VarsUpdate.as_view(), name='vars_update'),
]

app_name = "tasks"

tasks/models.py
from django.db import models
from django_celery_results.models import TaskResult
from jsonfield import JSONField
from asset.models import AssetInfo

__all__ = [
    'Tools',
    'ToolsResults',
    'Variable'
]
cmd_list = [
    'shell',
]


class Tools(models.Model):
    TOOL_RUN_TYPE = (
        ('shell', 'shell'),
        ('python', 'python'),
        ('yml', 'yml'),
    )

    name = models.CharField(max_length=255, verbose_name='工具名称', unique=True)
    tool_script = models.TextField(verbose_name='脚本', null=True, blank=True)
    tool_run_type = models.CharField(choices=TOOL_RUN_TYPE, verbose_name='脚本类型', max_length=24)
    comment = models.TextField(verbose_name='工具说明', null=True, blank=True)

    ctime = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    utime = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    def __str__(self):
        return self.name

    class Meta:
        db_table = "Tools"
        verbose_name = "工具"
        verbose_name_plural = verbose_name


class ToolsResults(models.Model):
    task_id = models.UUIDField(max_length=255, verbose_name='任务ID', unique=True)
    add_user = models.CharField(max_length=255, verbose_name='创建者', null=True, blank=True)
    ctime = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    @property
    def status(self):
        status = TaskResult.objects.get(task_id=self.task_id).status
        return status

    class Meta:
        db_table = "ToolsResults"
        verbose_name = "任务"
        verbose_name_plural = verbose_name


class Variable(models.Model):
    name = models.CharField(max_length=200, verbose_name='变量组名字')
    desc = models.TextField(null=True, blank=True, verbose_name='描述')
    vars = JSONField(null=True, blank=True, default={}, verbose_name='变量')
    assets = models.ManyToManyField(AssetInfo, verbose_name='关联资产', related_name='asset', blank=True)

    ctime = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    utime = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    def __str__(self):
        return self.name

    class Meta:
        db_table = "Variable"
        verbose_name = "变量组"
        verbose_name_plural = verbose_name

tasks/views.py
from django.shortcuts import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, View, CreateView, UpdateView, DetailView
from django.db.models import Q
from asset.models import AssetInfo, AssetProject
from tasks.models import cmd_list, Tools, ToolsResults, Variable
from tasks.form import ToolsForm, VarsForm
from tasks.tasks import ansbile_tools
from django_celery_results.models import TaskResult
from index.password_crypt import decrypt_p
from chain import settings
from name.models import Names
from tasks.ansible_2420.runner import AdHocRunner
from tasks.ansible_2420.inventory import BaseInventory
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
import json, datetime, paramiko, os, logging, random, time

logger = logging.getLogger('tasks')
from pure_pagination import PageNotAnInteger, Paginator

class TasksCmd(LoginRequiredMixin, ListView):
    """
    任务cmd 界面
    """
    template_name = 'tasks/cmd.html'
    model = AssetInfo
    context_object_name = "asset_list"
    queryset = AssetInfo.objects.all()
    ordering = ('-id',)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = {
            "tasks_active": "active",
            "tasks_cmd_active": "active",
            "cmd_list": cmd_list,
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        """
         资产查询功能
        """
        name = Names.objects.get(username=self.request.user)
        self.queryset = super().get_queryset()
        for i in self.queryset:
            project = AssetInfo.objects.get(hostname=i)
            project_obj = AssetProject.objects.filter(projects=project)
            hasperm = name.has_perm('cmd_assetproject', project_obj)
            if not hasperm:
                self.queryset.delete(i)

        if self.request.GET.get('project'):
            project = self.request.GET.get('project', None)
            business = self.request.GET.get('business', None)
            if business is not None:
                pro = AssetProject.objects.get(id=int(project)).projects
                self.queryset = self.queryset.filter(Q(project__projects=pro), Q(business__business=business)).order_by(
                    '-id')
            else:
                self.queryset = self.queryset.filter(Q(project__projects=project)).order_by('-id')
        return self.queryset


class TasksTail(LoginRequiredMixin, ListView):
    """
    任务 tail_log  界面
    """
    template_name = 'tasks/tail.html'
    model = AssetInfo
    context_object_name = "asset_list"
    queryset = AssetInfo.objects.all()
    ordering = ('-id',)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = {
            "tasks_active": "active",
            "tasks_tail_active": "active",
            "cmd_list": cmd_list,
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        """
         资产查询功能
        """
        name = Names.objects.get(username=self.request.user)
        self.queryset = super().get_queryset()
        for i in self.queryset:
            project = AssetInfo.objects.get(hostname=i)
            project_obj = AssetProject.objects.filter(projects=project)
            hasperm = name.has_perm('cmd_assetproject', project_obj)
            if not hasperm:
                self.queryset.delete(i)

        if self.request.GET.get('project'):
            project = self.request.GET.get('project', None)
            business = self.request.GET.get('business', None)
            if business is not None:
                pro = AssetProject.objects.get(id=int(project)).projects
                self.queryset = self.queryset.filter(Q(project__projects=pro), Q(business__business=business)).order_by(
                    '-id')
            else:
                self.queryset = self.queryset.filter(Q(project__projects=project)).order_by('-id')
        return self.queryset


def cmdjob(assets, tasks):
    """
    :param assets:  资产帐号密码
    :param tasks:  执行的命令 和 模块
    :return:  执行结果
    """

    inventory = BaseInventory(host_list=assets)
    hostname = []
    for i in inventory.hosts:
        hostname.append(i)
    runner = AdHocRunner(inventory)
    retsult = runner.run(tasks, "all")
    ret = None
    try:
        ok = retsult.results_raw['ok']
        failed = retsult.results_raw['failed']
        unreachable = retsult.results_raw['unreachable']
        if not ok and not failed:
            ret = unreachable
        elif not ok:
            ret = failed
        else:
            ret = ok
    except Exception as e:
        logger.error("{}".format(e))

    retsult_data = []

    for i, element in enumerate(hostname):
        std, ret_host = [], {}
        for t in range(len(tasks)):
            try:
                out = ret[element]['task{}'.format(t)]['stdout']
                err = ret[element]['task{}'.format(t)]['stderr']
                std.append("{0}{1}".format(out, err))
            except Exception as e:
                logger.error(e)
                try:
                    std.append("{0} \n".format(
                        ret[hostname[i]]['task{}'.format(t)]['msg'], t + 1))
                except Exception as e:
                    logger.error("第{0}个执行失败,此任务后面的任务未执行 {1}".format(t + 1, e))
                    std.append("第{0}个执行失败,此任务后面的任务未执行".format(t + 1))

        ret_host['hostname'] = element
        ret_host['data'] = '\n'.join(std)
        retsult_data.append(ret_host)

    return retsult_data


def taillog(request, hostname, port, username, password, private, tail):
    """
    执行 tail log 接口
    """
    channel_layer = get_channel_layer()
    user = request.user.username
    os.environ["".format(user)] = "true"
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    if password:
        ssh.connect(hostname=hostname, port=port, username=username, password=decrypt_p(password))
    else:
        pkey = paramiko.RSAKey.from_private_key_file("{0}".format(private))
        ssh.connect(hostname=hostname, port=port, username=username, pkey=pkey)
    cmd = "tail " + tail
    stdin, stdout, stderr = ssh.exec_command(cmd, get_pty=True)
    for line in iter(stdout.readline, ""):
        if os.environ.get("".format(user)) == 'false':
            break
        result = {"status": 0, 'data': line}
        result_all = json.dumps(result)
        async_to_sync(channel_layer.group_send)(user, {"type": "user.message", 'text': result_all})


class TasksPerform(LoginRequiredMixin, View):
    """
    执行 cmd  命令
    """

    @staticmethod
    def post(request):
        name = Names.objects.get(username=request.user)
        ids = request.POST.getlist('id')
        args = request.POST.getlist('args', None)
        modules = request.POST.getlist('module', None)
        ret_data = {'data': []}
        if not ids or args == [''] or not modules:
            ret = {'hostname': None, 'data': "请选中服务器,输入要执行的命令"}
            ret_data['data'].append(ret)
            return HttpResponse(json.dumps(ret_data))

        idstring = ','.join(ids)
        asset_obj = AssetInfo.objects.extra(where=['id IN (' + idstring + ')'])

        for i in asset_obj:
            project = AssetInfo.objects.get(hostname=i).project
            project_obj = AssetProject.objects.get(projects=project)
            hasperm = name.has_perm('cmd_assetproject', project_obj)
            if not hasperm:
                return HttpResponse(status=500)

        tasks, assets = [], []
        for x in range(len(modules)):
            tasks.append(
                {"action": {"module": modules[x], "args": args[x]}, "name": 'task{}'.format(x)}, )

        for i in asset_obj:
            try:
                i.user.hostname
            except Exception as e:
                logger.error(e)
                ret = {
                    'hostname': i.hostname,
                    'data': '未关联用户,请关联后再操作  {0}'.format(e)}
                ret_data['data'].append(ret)
                return HttpResponse(json.dumps(ret_data))

            var_all = {
                'hostname': i.hostname,
                'inner_ip': i.inner_ip,
                "network_ip": i.network_ip,
                "project": i.project.projects}
            try:
                var_all.update(Variable.objects.get(assets__hostname=i).vars)
            except Exception as e:
                pass
            assets.append({
                "hostname": i.hostname,
                "ip": i.network_ip,
                "port": i.port,
                "username": i.user.username,
                "password": decrypt_p(i.user.password),
                "private_key": i.user.private_key.name,
                "vars": var_all,
            }, )
        t = cmdjob(assets, tasks)
        ret_data['data'] = t
        return HttpResponse(json.dumps(ret_data))


def taskstailperform(request):
    """
    执行 tail_log  命令
    """
    if request.method == "POST":
        ret = {'status': True, 'error': None, }
        name = Names.objects.get(username=request.user)
        ids = request.POST.get('id')
        tail = request.POST.get('tail', None)

        if not ids or not tail:
            ret['status'] = False
            ret['error'] = "请选择服务器,输入参数及日志地址."
            return HttpResponse(json.dumps(ret))

        asset_obj = AssetInfo.objects.get(id=ids)
        project_obj = AssetProject.objects.get(projects=asset_obj.project)
        hasperm = name.has_perm('cmd_assetproject', project_obj)
        if not hasperm:
            return HttpResponse(status=500)
        try:
            taillog(request, asset_obj.network_ip, asset_obj.port, asset_obj.user.username, asset_obj.user.password,
                    asset_obj.user.private_key, tail)
        except Exception as e:
            ret['status'] = False

templates/tasks/tools.html
{% extends "base.html" %}


{% block  title %}脚本工具{% endblock %}

{% block page-content %}



    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>脚本工具</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a>作业中心</a>
                </li>
                <li class="active">
                    <strong>脚本工具</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>脚本工具</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项 1</a>
                                </li>
                                <li><a href="#">选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                          <div class="table-responsive">

                            <a href="{% url    'tasks:tools_add' %}" class="btn btn-primary  ">
                                添加</a>

                            <a class="btn btn-danger tools_all_del"
                              >批量删除
                            </a>





                            <form id="del_form_tools_bulk" class="form-horizontal  ">

                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>
                                    <tr>
                                        <th width="20"><input type="checkbox" id="CheckedAll"></th>
                                        <th>名称</th>
                                        <th>脚本类型</th>
                                        <th>工具说明</th>
                                        <th>更新时间</th>

                                         <th>动作</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for   row   in   tools_list %}

                                        <tr class="gradeA" id="{{ row.id }}">
                                            <td><input  type="checkbox"   value="{{ row.id }}"   name="id"></td>
                                            <td class="center">{{ row.name }}</td>
                                            <td class="center"><div class="label label-success">{{ row.tool_run_type }}</div>  </td>
                                            <td class="center">{{ row.comment }}</td>
                                            <td class="center">{{ row.utime }}</td>

                                            <td>
                                                <a class="btn btn-primary  btn-xs "
                                                   href="{% url  "tasks:tools_update"   pk=row.id   %}">编辑</a>
                                                <a class="btn btn-danger  btn-xs  tools_del"
                                                      >删除
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>

                                </table>


                            </form>


                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>


{% block footer-js %}

<script>
            $(function () {
                 $(document).on('click','.tools_del',function () {


                    var   id = $(this).parent().parent().attr('id');


                   swal({

                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",

                        closeOnConfirm: false
                    }, function () {
                    $.ajax({
                         url: "{% url "tasks:tools_bulk_delete" %}",
                        type: 'POST',
                       data: {'nid': id},
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        })
                    });
                });

  $(document).on('click','.tools_all_del',function () {




                       swal({

                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",

                        closeOnConfirm: false
                    }, function () {
                    $.ajax({
                        url: "{% url "tasks:tools_bulk_delete" %}",
                        type: 'POST',
                        data: $('#del_form_tools_bulk').serialize(),
                         success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        })
                    });
                });
 });

</script>


{% endblock %}

{% endblock %}

templates/tasks/vars.html
{% extends "base.html" %}


{% block  title %}主机变量{% endblock %}

{% block page-content %}



    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>主机变量</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a>作业中心</a>
                </li>
                <li class="active">
                    <strong>主机变量</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>主机变量</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项 1</a>
                                </li>
                                <li><a href="#">选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                          <div class="table-responsive">

                            <a href="{% url    'tasks:vars_add' %}" class="btn btn-primary  ">
                                添加</a>

                            <a class="btn btn-danger vars_all_del"
                              >批量删除
                            </a>





                            <form id="del_form_tools_bulk" class="form-horizontal  ">

                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>
                                    <tr>
                                        <th width="20"><input type="checkbox" id="CheckedAll"></th>
                                        <th>名称</th>

                                        <th>描述</th>


                                         <th>动作</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for   row   in   vars_list %}

                                        <tr class="gradeA" id="{{ row.id }}">
                                            <td><input  type="checkbox"   value="{{ row.id }}"   name="id"></td>
                                            <td class="center">{{ row.name }}</td>
                                            <td class="center">{{ row.desc }}  </td>


                                            <td>
                                                <a class="btn btn-primary  btn-xs "
                                                   href="{% url  "tasks:vars_update"   pk=row.id   %}">编辑</a>
                                                <a class="btn btn-danger  btn-xs  vars_del"
                                                      >删除
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>

                                </table>


                            </form>


                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>


{% block footer-js %}

<script>
            $(function () {
                 $(document).on('click','.vars_del',function () {


                    var   id = $(this).parent().parent().attr('id');


                   swal({

                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",

                        closeOnConfirm: false
                    }, function () {
                    $.ajax({
                         url: "{% url  'tasks:vars_bulk_delete' %}",
                        type: 'POST',
                       data: {'nid': id},
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        })
                    });
                });

  $(document).on('click','.vars_all_del',function () {




                       swal({

                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",

                        closeOnConfirm: false
                    }, function () {
                    $.ajax({
                        url: "{% url  'tasks:vars_bulk_delete' %}",
                        type: 'POST',
                        data: $('#del_form_tools_bulk').serialize(),
                         success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        })
                    });
                });
 });

</script>


{% endblock %}

{% endblock %}